### PR TITLE
action-31-setup-action-for-formatting-and-linting

### PR DESCRIPTION
**Pull request by JacquelineFriedberg**
Setup of GitHub action that formats and lints files on git push & PR.

See: 
[`.github/workflows/format-and-lint.yml` ](https://github.com/She-Codes-PCC/website/blob/setup-github-actions/.github/workflows/format-and-lint.yml)

 Steps:
 - Fix formatting for js,jsx,css,md,mdx,yaml,yml,toml
 - Fix lint for js
 - Fix lint for CSS
 - Commit changes with comment `Commit from GitHub Actions (Format and Lint CI)`

[View Checks](https://github.com/She-Codes-PCC/website/runs/4415165937?check_suite_focus=true)

Thank you: 
@hyperupcall helped w/ `if: always()` & `- uses: EndBug/add-and-commit@v7`

### CODE REVIEW

**Review by shelbiooley — APPROVED** [review]
looks good, would just consider deleting the test files(if they are no longer needed) before merging

**Comment by hyperupcall** [comment]
Awesome! You might have already been thinking this, but I'll say it anyways - it might be good to "Merge and squash" this PR so all these commits don't show up when merged :stuck_out_tongue_winking_eye:

**Comment by JacquelineFriedberg** [comment]
Yeah there are a lot of commits for sure lol

**Review by sorata000x — APPROVED** [review]
Great works! (sorry I wasn't able to help much of it)

**Comment by JacquelineFriedberg** [comment]
@sorata000x You have applications! That's amazing great work! And, when you were testing the node actions it really helped me learn too! So, thank you!

**Pull request merged**
