### PR TITLE
Template 66 setup base nextjs website

### PR DESCRIPTION
**Pull request by JacquelineFriedberg**
Hello
@camille-marcojos @shelbiooley Great work on this thing here. It looks great! 

## We created base Next.js Template w/ 
- `Yarn create next-app`
- [RMWC](https://rmwc.io/)  style stuff

@hyperupcall Made a few edits. Let us know if anything needs to be changed:
## ESLint Changes:  
  - Changed to Google lint config because of the numerous errors on AirBnb
    - Removed `eslint-config-airbnb` from `package.json`
    - Added `google` and `next` to `.eslintrc.json`
    - Added `eslint-config-google` to `package.json`
    - Turned off Require JSDoc on`.eslintrc.json` by adding: ` "rules": { “require-jsdoc": "off"}` 			 

## Fixed `format-lint.yml`
  - Added `.github/` to `.prettierignore` will look for other options in future.    

##  Requires: `yarn install`
  - Note: Since peeps will be adding new `RMWC` node modules on the regular... can think of ways of adding yarn install when peeps `pull`

### CODE REVIEW

**Comment by hyperupcall** [comment]
I made a few edits, with some elaboration in the extended commit message :)

**Comment by JacquelineFriedberg** [comment]
@hyperupcall 
Cool! LGTM 👍

> > Note: Since peeps will be adding new RMWC node modules on the regular... can think of ways of adding yarn install when peeps pull
> 
> We might be able to do something like this with [Husky](https://github.com/typicode/husky), which automates creating specialized Git hooks. Usually, you would automate it to do something on `git add` (like run tests). But I don't think I would recommend doing it for `git install`, or the like, since that sort of behavior can be confusing, even if it is a bit convenient.

Cool. That makes sense.

**Comment by sorata000x** [comment]
Looks good, great work!

**Review by sorata000x — APPROVED** [review]
Looks good, great work!

**Pull request merged**
