### PR TITLE
Configure formatters and linters

### PR DESCRIPTION
**Pull request by hyperupcall**
This adds configuration that properly sets up the following
 
- [EditorConfig](https://editorconfig.org)
- [Prettier](https://prettier.io) (formatter, reads from `.prettierrc.json` and mostly `.editorconfig`)
- [ESLint](https://eslint.org) (JS linter)
- [Stylelint](https://stylelint.io) (CSS linter)
- VSCode (integration with the previous tools via extensions and json files in `./.vscode`)

Some nifty features:

- Automatically fix formatting issues (tabs instead of spaces, etc.) with Pretiter and the EditorConfig config
- Automatically fix JS linting issues (sort `import` statements, use `let` instead of `var`, etc.)
- Automatically fix CSS linting issues (wrong units, duplicate statements, etc.)
- Configured [VSCode tasks](https://code.visualstudio.com/docs/editor/tasks)
	- Start NextJS Server
	- Fix formatting errors 
	- Fix JS and CSS linting errors
- Configured [npm scripts](https://docs.npmjs.com/cli/v8/using-npm/scripts)
	- `yarn run lint` to fix formatting errors
	- `yarn run format` to fix js / css linting errors

There are complimentary tools like [Husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged), but they are not as important as the tools that I have currently setup

### CODE REVIEW

**Review by sorata000x — APPROVED** [review]
Awesome

**Comment by JacquelineFriedberg** [comment]
@hyperupcall This looks great. I'm just going to make a few changes. Can review them.

**Comment by JacquelineFriedberg** [comment]
@hyperupcall 
- added comments
- contributing file
- changed tabs to 2 spaces
- added tests w/ comments for contributors 
- added format on paste, type

can edit 

After this can hold on merge. Will notify Shelbi when done so she can add it to her contributing files.

**Comment by hyperupcall** [comment]
@JacquelineFriedberg Awesome, there are two things I would note though

- I wouldn't recommend adding`"editor.formatOn{Paste,Type}"` to the config. Those are closer to a personal preference and many people (myself included) leave them disabled for performance reasons (and because it can be buggy at times). `"editor.formatOnSave"` is the least intrusive option and is the least common denominator
- I _highly_ recommend using tabs over spaces. I'd like to discuss in detail, but in short tabs are quite powerful since they are inherently more accessible (reading impairments), and flexible (per-programmer customizable widths)

**Comment by JacquelineFriedberg** [comment]
@hyperupcall 
Think will turn the test files into gifs and add them to CONTRIBUTING.md so peeps can learn a few things. The tabs and only format on save makes sense.

**Comment by hyperupcall** [comment]
@JacquelineFriedberg Sounds good ^w^

**Comment by JacquelineFriedberg** [comment]
@hyperupcall @sorata000x K. Think it's pretty good. Let me know if needs any edits. Otherwise, will let Shelbi know it's all good to add to the contributing file.

**Comment by JacquelineFriedberg** [comment]
@shelbiooley Hi! These files are ready to add to your contributing work. 

Here is info from Nelson: https://github.com/She-Codes-PCC/website/pull/53#issue-1059494831

And, the contributing file includes some instructions that might help contributors

Feel free to edit.

**Comment by JacquelineFriedberg** [comment]
@shelbiooley Hi! These files are ready to add to your contributing work. 

Here is [info from Edwin](https://github.com/She-Codes-PCC/website/pull/53#issue-1059494831)

And, the contributing file includes some instructions that might help contributors.

**Review by shelbiooley — APPROVED** [review]
sorry it took me a bit to get to this, but it all looks good, thanks!

**Comment by JacquelineFriedberg** [comment]
@shelbiooley All good! Hope Thanksgiving was great. Whenever are ready if want can add ur contributing work to this branch or let us know a diff next best step.

**Comment by shelbiooley** [comment]
I have a separate branch that I am using to write the contributing.md file. If one other person can review and approve this pull request then you guys can go ahead and merge when you are ready

**Comment by JacquelineFriedberg** [comment]
@shelbiooley Sounds good. Thanks!

**Review by JacquelineFriedberg — APPROVED** [review]

**Pull request merged**
